version: "3.3"

services:
  notebook:
    #image: jupyter/tensorflow-notebook
    build: build/.
    container_name: jupyter
    hostname: jupyter
    restart: unless-stopped
    volumes:
      - ./work:/home/jovyan/work
      - ./jupyter_notebook_config.py:/root/.jupyter/jupyter_notebook_config.py
    ports:
      - 9999:8888
    environment:
      - TZ=Asia/Taipei
      - JUPYTER_ENABLE_LAB=yes
      - GRANT_SUDO=yes
